#!/bin/bash
case $# in
  3) HOSTPORT=${1}
     TOPIC=${2}
     WATCHEDFILE=${3};;
  *) echo "Usage: cpost <hostport> <topic> <filename>" > /dev/stderr
      exit -1;;
esac

while true; do
        inotifywait -e modify ${WATCHEDFILE} && CONTENT=$(since ${WATCHEDFILE})
        if [ -n "${CONTENT}" ]; then
                while read -r line
                do
                        echo $line | curl -XPOST "http://${HOSTPORT}/cyclops/publish/${TOPIC}" -d @- -H 'Content-Type:text/plain'
                done <<< "${CONTENT}"
        fi
done
