#!/usr/bin/env python
#!/usr/bin/python
import websocket
import thread
import time
import sys
import json

def on_message(ws, message):
    try:
        event = json.loads(message)
        print event['message']
    except Exception:
        print message

def on_error(ws, error):
	print error

def on_close(ws):
	#print "### closed ###"
	pass

def on_open(ws):
	#print "opened connection"
	pass

if __name__ == "__main__":
	topic = sys.argv[2]
	websocket.enableTrace(True)
	ws = websocket.WebSocketApp("ws://" + sys.argv[1] + ":9030/cyclops/notify/"+topic,
								on_message = on_message,
								on_error = on_error,
								on_close = on_close)
	ws.on_open = on_open

	ws.run_forever()
